name: Unittest - shunit2
on:
  workflow_dispatch
  push:
  pull_request:
jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Unittest
        run: |
          cd tests
          ./runner.sh

